name: test syntax

on:
  pull_request:
    branches:
    - main

jobs:
  syntax-check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.97.3'
        extended: true

    - name: Build
      run: hugo --gc --minify --cleanDestinationDir

    - name: (British/American) English test
      # Content should be written in American English. Test all content against
      # British English spelling list from:
      # http://www.tysto.com/uk-us-spelling-list.html'
      shell: bash
      run: .github/workflows/english_test.sh
